In [38]:
import numpy as np

x1=[0,0,1,1]
x2=[0,1,0,1]
OP=[0,1,1,0]
w1=0.45
w2=0.56
b=0.33
number_of_epochs=1500

In [34]:
def sigmoid(z):
    return 1/(1+np.exp(-z))

for epoch in range(1,number_of_epochs+1):
    print(f'Epoch Number:{epoch}')
    for iter in range(len(OP)):
        z=w1*x1[iter]+w2*x2[iter]
        print(f'calculated z:{z}')
        P=sigmoid(z)
        print(f'predicted Value:{P}')
        cost_val=(P-OP[iter])**2
        print(f'cost value: {cost_val}')
        #print(f'iter number:{iter}')
    print('--'*25)


Epoch Number:1
calculated z:0.0
predicted Value:0.5
cost value: 0.25
calculated z:0.56
predicted Value:0.6364525402815664
cost value: 0.1321667554677261
calculated z:0.45
predicted Value:0.610639233949222
cost value: 0.15160180613964866
calculated z:1.01
predicted Value:0.7330201492388575
cost value: 0.5373185391901569
--------------------------------------------------
Epoch Number:2
calculated z:0.0
predicted Value:0.5
cost value: 0.25
calculated z:0.56
predicted Value:0.6364525402815664
cost value: 0.1321667554677261
calculated z:0.45
predicted Value:0.610639233949222
cost value: 0.15160180613964866
calculated z:1.01
predicted Value:0.7330201492388575
cost value: 0.5373185391901569
--------------------------------------------------
Epoch Number:3
calculated z:0.0
predicted Value:0.5
cost value: 0.25
calculated z:0.56
predicted Value:0.6364525402815664
cost value: 0.1321667554677261
calculated z:0.45
predicted Value:0.610639233949222
cost value: 0.15160180613964866
calculated z:1.01
p

In [76]:
import numpy as np
h=0.0001
alpha=0.01
def cost(w1,w2,b,A,x1,x2):
    z=w1*x1+w2*x2+b
    p=1/(1+np.exp(-z))
    return (p-A)**2

for epoch in range(1,number_of_epochs+1):
    print(f'Epoch number:{epoch}')
    for iter in range(len(OP)):
        d_J_w1=cost(w1,w2,b,OP[iter],x1[iter],x2[iter])
        d_j_w1_h=cost(w1+h,w2,b,OP[iter],x1[iter],x2[iter])
        d_w1=(d_J_w1-d_j_w1_h)/h
    print('---'*25)

    for iter in range(len(OP)):
        d_J_w2=cost(w1,w2,b,OP[iter],x1[iter],x2[iter])
        d_j_w2_h=cost(w1,w2+h,b,OP[iter],x1[iter],x2[iter])
        d_w2=(d_J_w2-d_j_w2_h)/h
    print('---'*25)

    for iter in range(len(OP)):
        d_J_b=cost(w1,w2,b,OP[iter],x1[iter],x2[iter])
        d_j_b_h=cost(w1,w2,b+h,OP[iter],x1[iter],x2[iter])
        d_b=(d_J_b-d_j_b_h)/h
    print('---'*25)
    w1=w1-alpha*d_w1
    w2=w2-alpha*d_w2
    b=b-alpha*d_b

    #print(w1,w2,b)

sigmoid(w1*1+w2*0+b)





Epoch number:1
---------------------------------------------------------------------------
---------------------------------------------------------------------------
---------------------------------------------------------------------------
Epoch number:2
---------------------------------------------------------------------------
---------------------------------------------------------------------------
---------------------------------------------------------------------------
Epoch number:3
---------------------------------------------------------------------------
---------------------------------------------------------------------------
---------------------------------------------------------------------------
Epoch number:4
---------------------------------------------------------------------------
---------------------------------------------------------------------------
---------------------------------------------------------------------------
Epoch number:5
-------------

0.9809752649748797

In [36]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers,models

model=models.Sequential()
model.add(layers.Dense(64,activation='relu', input_dim=2))
model.add(layers.Dense(1,activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer='sgd',metrics=['accuracy'])


c:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [64]:
import pandas as pd

data=pd.DataFrame(columns=['x1','x2','OP'])
data['x1']=x1
data['x2']=x2
data['OP']=OP

X=data.drop(columns='OP').values
print(X)
y=np.array(data['OP']).reshape(-1,1)
print(y)

model.fit(X,y,epochs=300)


[[0 0]
 [0 1]
 [1 0]
 [1 1]]
[[0]
 [1]
 [1]
 [0]]
Epoch 1/2000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 1.0000 - loss: 0.1233
Epoch 2/2000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 1.0000 - loss: 0.1232
Epoch 3/2000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 1.0000 - loss: 0.1232
Epoch 4/2000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 1.0000 - loss: 0.1231
Epoch 5/2000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 1.0000 - loss: 0.1230
Epoch 6/2000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 1.0000 - loss: 0.1230
Epoch 7/2000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - accuracy: 1.0000 - loss: 0.1229
Epoch 8/2000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 1.0000 - loss: 0.1229
Epoch 9/2000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 1.0000 - loss: 0.1228
Epoch 10/2000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 1.0000 - loss: 0.1228
Epoch 11/2000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 1.0000 - loss: 0.1227
Epoch 12/2000

In [77]:
import tensorflow as tf

In [101]:
model.predict(np.array([[0,1]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step


array([[0.41747537]], dtype=float32)

In [99]:
import numpy as np

x1=[0,0,0,0,1,1,1,1]
x2=[0,0,1,1,0,0,1,1]
x3=[0,1,0,1,0,1,0,1]
OP=[0,1,1,1,1,1,1,0]
w1=0.45
w2=0.56
b=0.33
number_of_epochs=1500

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers,models

model=models.Sequential()
model.add(layers.Dense(64,activation='relu', input_dim=2))
model.add(layers.Dense(1,activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer='sgd',metrics=['accuracy'])


c:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [100]:
import pandas as pd

data=pd.DataFrame(columns=['x1','x2','x3','OP'])
data['x1']=x1
data['x2']=x2
data['x3']=x3
data['OP']=OP

X=data.drop(columns='OP').values
print(X)
y=np.array(data['OP']).reshape(-1,1)
print(y)

model.fit(X,y,epochs=300)

[[0 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 1]
 [1 0 0]
 [1 0 1]
 [1 1 0]
 [1 1 1]]
[[0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]]
Epoch 1/300


ValueError: Exception encountered when calling Sequential.call().

Input 0 of layer "dense_28" is incompatible with the layer: expected axis -1 of input shape to have value 2, but received input with shape (None, 3)

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=(None, 3), dtype=int64)
  • training=True
  • mask=None

In [102]:
data=pd.read_csv(r'c:\Users\user\Downloads\truth_table.csv')
display(data)

A  B  C  D  Output
0   0  0  0  0       1
1   1  0  0  0       0
2   0  1  0  0       0
3   1  1  0  0       1
4   0  0  1  0       0
5   1  0  1  0       1
6   0  1  1  0       1
7   1  1  1  0       0
8   0  0  0  1       0
9   1  0  0  1       1
10  0  1  0  1       1
11  1  1  0  1       0
12  0  0  1  1       1
13  1  0  1  1       0
14  0  1  1  1       0
15  1  1  1  1       1

In [103]:
import numpy as np
w1=0.45
w2=0.56
b=0.33
number_of_epochs=1500

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers,models

model=models.Sequential()
model.add(layers.Dense(64,activation='relu', input_dim=2))
model.add(layers.Dense(1,activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer='sgd',metrics=['accuracy'])

c:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [104]:
import pandas as pd
A=[]
B=[]
C=[]
D=[]
Output=[]

data=pd.DataFrame(columns=['A','B','C','D','Output'])
data['A']=A
data['B']=B
data['C']=C
data['D']=D
data['Output']=Output

X=data.drop(columns='Output').values
print(X)
y=np.array(data['Output']).reshape(-1,1)
print(y)

model.fit(X,y,epochs=300)

[]
[]
Epoch 1/300


ValueError: Exception encountered when calling Sequential.call().

Input 0 of layer "dense_30" is incompatible with the layer: expected axis -1 of input shape to have value 2, but received input with shape (32, 4)

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=(32, 4), dtype=float32)
  • training=True
  • mask=None